# Generated by Django 4.0.2 on 2022-07-09 17:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import iranian_cities.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iranian_cities', '0004_remove_abadi_shhahr'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد تخفیف')),
                ('valid_from', django_jalali.db.models.jDateTimeField(verbose_name='از')),
                ('valid_to', django_jalali.db.models.jDateTimeField(verbose_name='تا')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='درصد تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False, verbose_name='خریده شده')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postalcode', models.PositiveIntegerField(default=0, verbose_name='کد پستی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات پست')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('discount', models.IntegerField(blank=True, default=None, null=True, verbose_name='تخفبف')),
                ('code', models.CharField(max_length=200, null=True, verbose_name='کد سفارش')),
                ('tracking_post', models.BigIntegerField(blank=True, null=True, verbose_name='کد رهگیری')),
                ('ostan', iranian_cities.fields.OstanField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan', verbose_name='استان')),
                ('shahrestan', iranian_cities.fields.ShahrestanField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahrestan', verbose_name='شهرستان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.variant')),
            ],
        ),
    ]
